apiVersion: apps/v2
kind: Deployment
metadata:
  name: new-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-php-app
  template:
    metadata:
      labels:
        app: new-php-app
    spec:
      containers:
      - name: new-php-app
        image: devopspk93/php-project
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v2
kind: Service
metadata:
  name: phpapp-service
spec:
  selector:
    app: php-project1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
