apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app3
  template:
    metadata:
      labels:
        app: php-app3
    spec:
      containers:
      - name: php-app3
        image: devopspk93/php-project
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-app3
spec:
  selector:
    app: php-app3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
