apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-php-app
  template:
    metadata:
      labels:
        app: new-php-app
    spec:
      containers:
      - name: php-app10
        image: devopspk93/new-php-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-service2
spec:
  selector:
    app: php-project1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
